services:
  # Client
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"  
    depends_on:
      - server
  
  # Server
  server:
    build: ./server
    restart: always
    ports:
      - "4000:4000" 
    depends_on:
      - db
      
  # Database
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # Root password
      MYSQL_DATABASE: tasks          # Default database
      MYSQL_USER: myuser             # Non-root user (optional)
      MYSQL_PASSWORD: myuserpassword # Password for the non-root user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
       - ./nginx/.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client

volumes:
  db_data:

networks:
  Default:
    driver: bridge
